### ISSUE TITLE
Fix the DS Remaster

### ISSUE THREAD

**Issue by AeliusSaionji** [Wulf2k/DaS-PC-MPChan#142]
If script kiddies can still use their cheats from DS1, surely DSCM would still work on the remaster with minimal effort.

Why?

1. Softbans suck. Fromsoft (and other parties involved) don't have the foresight or the expertise to do it even remotely competently- we're better off not having softbans at all. Especially since PvP Watchdog exists. Unless I misunderstand something, softbans wouldn't exist in DSCM unless you decided to add it.

2. Some of the new matchmaking rules are less than ideal. DSCM could allow us to play the good old DS way, and possibly allow users to opt-in to the new matchmaking logic?

Let me know if this is infeasible.

**Comment by metal-crow** [comment]
Unfortunately, softbans are enforced server side, and caused by the game doing anti-cheat detection and telling the server. The only way to prevent them is to stop the anti-cheat, which is a completely different area from DSCM (but being worked on!).

That said, porting DSCM would allow blocking and direct connections, although i don't believe those direct connections would be able to bypass the new weapon matchmaking mechanics (since that's either server side or client side, and if the other client isn't running DSCM they wouldn't allow the connection if its not normally allowed).

**Comment by metal-crow** [comment]
Also, a bit of detail: because of the way this anticheat works, it's actually harder for us to make real mods than it is for script kiddies to do basic stuff. We want to alter game _code_, which the anti-cheat detects, but all script kiddies do is change game _memory_.

**Comment by AeliusSaionji** [comment]
Looks like this is unlikely, then. I'll close this.

Thanks for the explanations!
