### ISSUE TITLE
Apparent error reading modules on load

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#62]
https://www.reddit.com/r/darksouls/comments/4ilq2x/dscm_dark_souls_connectivity_mod/d32l6do?context=3

Looks like your old concern about attaching too early wasn't unfounded.

Maybe encase it in a try and abort the attach on fail, assume it'll be fine on one of the next few attempts?

**Comment by Chronial** [comment]
If this actually a too early issue, I think it's better to just wait for 500ms between finding the process and attaching to it. That should definitely be enough time for DS to do its initial startup, and barely any user will notice. I don't think silently hiding errors is a good idea :wink:.

But I am not sure that this is actually the issue here. It is only that one user reporting the issue, right? I started DS hundreds of times during testing and never had a problem. Googling suggests that it could be a hardware or driver issue.

**Comment by Wulf2k** [comment]
It's only the one user, but if he waits and tries again it works.

**Comment by Chronial** [comment]
The auto-attach code [was already part](https://github.com/Wulf2k/DaS-PC-MPChan/commit/100492f5901840c1ef1ef99145a116b26908f68e) of the `DSCM-2016-05-06-01` release, with with the user did not have any problems.

**Comment by hydra-chan** [comment]
I get the same exception infrequently. The next time it pops up I'll copy over the debug log.

**Comment by Chronial** [comment]
I added a 200ms wait – let's see whether that stops it.

**Comment by Chronial** [comment]
closing this until someone reports it again.
