### ISSUE TITLE
[Suggestion] Smarter irc connection logic

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#9]
I think the IRC system would probably benefit from a smarter connection logic:
* It should prioritize players, instead of picking one at random
* It should take the nodecount of the target player into account (prioritize low nodecount) (shared via irc)
* It should make connections to "bad" (different SL / other Location) players if the nodecount is low. Bad is better than nothing.

I would propose this algorithm:
Sort all known nodes like this:
* First all players in the same region AND in SL coop range, sorted by nodecount
* Then all players in the same region OR in SL coop range, sorted by nodecount
* Then the rest, sorted by nodecount

Then try to connect to the first `x` in the list.

Remarks:
* This system can obviously be easily "cheated" by using a modified client that always reports a low nodecount. I don't think that is a real threat.
* It might be a good idea to "punish" nodes with 0 other nodes, as that might indicate connection problems? E.g. Of the `x` nodes, only `y` are allowed to have 0 nodes. But I would wait to see if that is actually a problem.
* I wouldn't just do this for low nodecounts, but also once every 5 minutes, assuming our nodecount is below 20. Maybe on those runs only take "perfect" (same region + coop range) nodes?

**Comment by Wulf2k** [comment]
I pick the first three that get reported just so that the built-in matchmaking has something to work with from that point.

The next (maxnode - 5) nodes get picked based off of a rough SL and World comparison.  It's definitely not perfect but it was a good enough way to get things started.

I'm not sure I really want to care about the nodecount.  If it's taking you to 15 nodes, then who really cares who they're connected to?  With that many connections at least some of them will be well connected, and if node count is ignored then it helps to bring in the lower node count players as well.

Right now it does it for (maxnodes - 5) nodecount, not just low nodecount.  The exact algorithm needs to be adjusted of course, but I want to leave a few free by default.  If it's trying to do stuff near maxnodes at the same time as Steam, whoever it adds could be immediately disconnected.
I also want to report covenant and sin, to match up blue invaders.  They need the help....

So anyway, I'm not committed to the way any of this code works, I mostly just wanted to get it live so that I could prove the concept would work well.

**Comment by Chronial** [comment]
I assumed your weren't done yet – this is why this is just text and not a PR ;).

My point about the nodecount was to strictly prefer players with lower nodecount. While this is of course worse for "me", I think the overall benefits to the community will clearly outweigh that. I would argue that it's much better to bring everybody up to a mediocre nodecount asap instead of just connecting randomly.

> Right now it does it for (maxnodes - 5) nodecount, not just low nodecount. 

I see, I misread the code there.

> I pick the first three that get reported just so that the built-in matchmaking has something to work with from that point.

Missed that too in my quick read. But I think this shouldn't be done at random, as you could do something smarter.

>  If it's trying to do stuff near maxnodes at the same time as Steam, whoever it adds could be immediately disconnected.

One more reason to prefer nodes with low nodecount ;).

**Comment by Wulf2k** [comment]
Ah, I'd misunderstood and thought you were advocating only connecting to high nodes.

I think I'll spend the rest of the weekend catching up on sleep and spending time with the family, maybe fixing any obvious bugs that pop up.  Once it's been tested a little more thoroughly and there's a larger pool of people to choose from I can get a little fancier.

It was also obviously a little difficult to do anything too complex while there were 0 people reporting.  =]

**Comment by Chronial** [comment]
I think the good parts of this are implemented.
