### ISSUE TITLE
Report timing and bandwidth discussion

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#90]
I don't have near enough time as I'd like these days to actually play Dark Souls so I figured I'd ask here.

Would increasing the time between reports cause any/much reduction in the quality of DSCM?

The individual bandwidth requirements of DSCM are pretty low but it's noticeable on my server already.  It's not exactly overloaded, but when I remote in I can feel it being a bit sluggish.  Running a constant ping to my server from outside has anywhere from 80-300 ms ping with occasional packet loss.

If we assume that usage will increase when I mark this version as stable then I could see things starting to degrade a bit.

Would doubling the reporting time be an issue in your opinion?

**Comment by Chronial** [comment]
> The individual bandwidth requirements of DSCM are pretty low but it's noticeable on my server already. It's not exactly overloaded, but when I remote in I can feel it being a bit sluggish

You can also definitely see that when you look at the IRC channel – the messages are delivered in chunks instead of an even flow. The server is clearly struggling a bit :/.

> Would doubling the reporting time be an issue in your opinion?

At the moment there are 150 DSCMs online and the network sees 1000 nodes. If every of the 150 DSCMs has 20 nodes, every of the 1000 nodes is connect to 3 DSCMs.
* In the worst case, it takes 5 minutes till you see a node the network knows about:
   * we check every 2 minutes if someone reported that node within the last 3 minutes. That makes 5 minutes till you hear about a node the worst case if you just joined.
* More likely, it will be average 1 minute, max 2 minutes (each DSCM takes responsibility for certain nodes and will publish their info every 2 minutes).
* we remove nodes we haven't heard of after 5 minutes
* Known-to-be-wrong data is updated in average every 40s (2 minutes / 3 connections)

So it depends – if you are in a less populated area, DSCM will have a harder time getting connections for you. Doubling these numbers means increasing the expected age of information to 80s. I don't know how long people stay in an area, and thus how likely this will make it that the data is actually incorrect.

These are just averages though. The bad cases are what we should be worried about. And that is: A node is only known to one DSCM. That means the information will be updated every 2 minutes. Increasing that to 4 minutes makes it quite likely that the data will be outdated IMHO.

----

But keep in mind that the load on your server should be about O(n²), so doubling the publish time will only increase the clients it can handle by 1.4. So I'm not sure whether this is the right way to go. But I also have to say I'm a little bit surprised that your server is hit like that. Since one client takes 1.5kb/s of bandwidth, your server should only have a usage of 225kb/s.

I was thinking that maybe we can move the channel to Quakenet. I read their rules and they at least don't directly forbid stuff like this. That would have the advantage that the mod has a good chance to continue working even if we both loose interest at some point. We would of course have to ask first ^^. What do you think?

**Comment by Chronial** [comment]
BTW: The server seems to be dying as we speak ^^. User count has just dropped to 50.

**Comment by gpotter2** [comment]
Question: is the IRC server sourcecode available somewhere ? (and in which language is it) ? So we may help you by trying to optimize it ? 

I understand it's the weakest part of DSCM-Net cause if there're bugs or security issues that would be painful... but still ?

**Comment by gpotter2** [comment]
Question: may we have your UnrealIRCD config source ? So we may help you optimizing it ?

**Comment by Wulf2k** [comment]
The server is currently jumping between 0.3% and 0.7% network utilization of the 1 gbps NIC.

I could put the config up somewhere if you think it's worth it, but I'm not sure what you'd be looking for.  There's no compression that I'm aware of that could be enabled, and the very text we're sending sets a hard minimum limit of the data that's being passed around.

I'm gonna go through and set the current testing as stable now and we can worry about it later.  The system is sufficient for now, but this would be the weakest point of it all.  I'll ponder solutions over the weekend.  Maybe it stops being broadcast, and instead I have a DSCM-BOT that everybody whispers their reports to, and it can...  do something with the data.  I dunno, I'm sleepy.

**Comment by Chronial** [comment]
What's CPU and RAM of the IRC process?

If we replace broadcast with a central server, I think it would make more sense to do this as a webservice. That would make hosting a lot easier.

**Comment by Wulf2k** [comment]
0% cpu, 13,700 KB RAM

The system itself isn't struggling, it seems to be entirely the upload speed as a bottleneck.

Since this is a residential connection I'll get absolutely no help from my ISP on that front.  Unless I want to start begging for donations and switch it to business class, but we're really, really not there yet.

**Comment by Chronial** [comment]
Ah, this is on your home connection? Well I guess that explains that :). I actually have a cloud server available. As it's a cheap box it only has 512 MB Ram, though. But if you say the IRC server only needs 15MB, I could just put it on there. If you want to go that route, tell me and I will see that I get a server set up.

**Comment by Wulf2k** [comment]
Well, it would solve the problem, but I don't want to impose.

If you "were" to get something up and running though, and it were just sitting there idle, I'd have no problem redirecting dscm.wulf2k.ca to it.

**Comment by Chronial** [comment]
I'll take a look ;)

**Comment by Chronial** [comment]
Server is running on `209.208.28.90:8123`. If you want, you can switch right now. I don't have access to my nameserver config at the moment, but tomorrow I will add a `dscm-net.chronial.de` record. I think it would be best if you then `CNAME` to that.

**Comment by Chronial** [comment]
k, dns is in place.

**Comment by Wulf2k** [comment]
Your server seems to be handling things well.

**Comment by Chronial** [comment]
Yes, it's looking good. We'll just have to see about bandwidth. I have one TB for free, after that it will be $0.02/GB by [my calculations](http://www.wolframalpha.com/input/?i=%283kB%2Fs+*+400+*+1+month+-+1TB%29+*+$0.02++%2F+GB) that could get expensive ^^. We might really have to turn this into a proper central service.

**Comment by Wulf2k** [comment]
Is that 1 TB "per month" free, or you just have 1 TB free of non-refreshing
bandwidth to burn through?

**Comment by Chronial** [comment]
That's per month. But my estimates put us at 4TB per month ^^

**Comment by Wulf2k** [comment]
Did I screw up the math here?

http://www.wolframalpha.com/input/?i=1.2mBps+*+1+month

**Comment by Chronial** [comment]
Where are the 1.2mBps coming from? My calculations say:
http://www.wolframalpha.com/input/?i=%283kB%2Fs+*+400+*+1+month+-+1TB%29+*+%240.02++%2F+GB

**Comment by Wulf2k** [comment]
3 kBps * 400 users = 1.2 mBps

WA interpreted that as Mbits per second, not MBytes in my link, so there's
the discrepancy.

**Comment by Wulf2k** [comment]
Are you able to monitor your remaining bandwidth in nearly real-time or do you just get surprised with a bill at the end of the month?

**Comment by Chronial** [comment]
I can monitor it. I'm at 25GB for this month, and don't really put any load on that except for the IRC.
This will be fine for up to one month – the donations would cover the costs, but we should look for a better solution within that month.

**Comment by Wulf2k** [comment]
I think P2P is out of the question if we want this to remain simple to use.

I see two ways of proceeding.

1)  We forget IRC channels and people just /msg a master-bot.  When they need nodes, they send a request to the bot and it /msgs them back with nodes to connect to.  This is probably the least hassle since we've already got the framework in place.

2)  We switch it to be purely SQL/web-based.  People submit their nodes and request matches.

**Comment by Chronial** [comment]
If I find the time I will just quickly whip together a webservice in python. I don't think this actually needs SQL – I will just keep the info in memory. If the service restarts, it will be quickly back to full info.

If I find some more time, I might even bridge it over to IRC, so we can make the transition without disturbing operations.

**Comment by Chronial** [comment]
This is no longer a problem since #98
